### ISSUE TITLE
ITS Theme Incompatibility? 

### ISSUE THREAD

**Issue by KeiranGinge** [gfxholo/iconic#13]
Hello! 

It appears that the ITS Theme, or a setting I cannot locate within it causes your icons to appear directly after the note title rather than in the normal position just before - Even if selecting the "Hide File Explorer Icons" within that Plugin's settings. Photo attached for reference.  ![image](https://github.com/gfxholo/iconic/assets/173967102/835024bf-3094-4a82-97f9-9341394bb433)

Otherwise - excellent implementation of this plugin, cannot wait to see it approved for Community release!

**Comment by gfxholo** [comment]
Thanks dude! ITS is a bit of a weird theme; it does some repositioning of the `tree-item-self` and `tree-item-icon` elements, which is easy to reverse since it's only CSS:

![#13a](https://github.com/gfxholo/iconic/assets/157357541/3d8b5d29-326a-4f7d-9ae5-6f5854c41fa8) ![#13b](https://github.com/gfxholo/iconic/assets/157357541/9bec6fbf-b790-4402-b129-a3d6d6db282f)

If it doesn't break anything else, I'll correct this in the plugin since I know it's a popular theme. 🦇

**Comment by KeiranGinge** [comment]
Amazing - I eagerly await the update! :)

**Comment by gfxholo** [comment]
It took a little more work than expected, but this should look waaaay better now @KeiranGinge.
